### ISSUE TITLE
Invalid path error during cloning

### ISSUE THREAD

**Issue by alexanderbartels96** [scrimba/learn-javascript#1]
When cloning the repo in GitHub Desktop, receive error code below : I'm on a Windows machine, maybe some illegal file names?

error: invalid path '1. Build a Passenger Counter App/18. What is a string?/index.css'

**Comment by cenkt** [comment]
İt is the question mark that is causing the error.

**Comment by alexanderbartels96** [comment]
Ah, thank you. Missed that.
